Feature/ITL-2
doramagyari/ToDoApp pull request #3
Opened 2024-03-14 14:30 UTC by doramagyari

2024-03-14 14:47 UTC, gerebdavid commented on src/components/ui/BaseDropdown.vue
> +          'rounded-full mr-4 p-1 h-6 text-white pt-0 px-6',
create a computed for the dynamic class

2024-03-14 14:50 UTC, kincsokiss requested changes

2024-03-14 14:50 UTC, kincsokiss commented on src/components/pages/TodoHome.vue
> +    <!-- <BaseButton @click="handleRemoveAllTodo">Clear All</BaseButton> -->
Please remove the unused code lines.

2024-03-14 14:50 UTC, gerebdavid commented on src/components/ui/BaseDropdown.vue
> +const priorities: string[] = ["Low", "Medium", "High"];
You should type priorities better, you can create a type from the priorities since you have predefined options as values.

2024-03-15 12:51 UTC, gerebdavid approved these changes

2024-03-15 12:59 UTC, merged