Feature/itl 4
doramagyari/ToDoApp pull request #5
Opened 2024-04-02 07:48 UTC by doramagyari

2024-04-02 13:52 UTC, kincsokiss requested changes

2024-04-02 13:52 UTC, kincsokiss commented on src/components/ui/BaseCard.vue
> +function todoChecked() {
Please make sure to use the proper function name and use actions or use `on` prefix if it's triggered for a specific event. For example: `checkTodo` or `onTodoChecked`

2024-04-02 13:52 UTC, kincsokiss commented on src/components/ui/BaseCard.vue
> +  emit("todo-checked", localTodo.value.id, localTodo.value.complete);
Same in the emit: `on-todo-checked`

2024-04-02 13:52 UTC, kincsokiss commented on src/components/ui/BaseCheck.vue
> +const emit = defineEmits(["update:modelValue", "checked-todo"]);
If you created a general component for Check, you shouldn't add the `todo` here in order not to change this to a specific component for Todos. 
In this case you can add everything as general as you can.
 For example:
 Change the `checked-todo` to `on-checked`
 The action should be handled here which is the checked, you don't need to specify what is checked.

2024-04-02 14:03 UTC, gerebdavid commented on src/components/pages/TodoHome.vue
> +  if (index !== -1) {
in cases like this its better to reverse the condition and use early return, so your code wont be indented a lot.

2024-04-03 07:02 UTC, merged

2024-04-03 11:05 UTC, gerebdavid commented on src/components/ui/BaseCard.vue
>          v-model="localTodo.title"
v-model should be higher than class

2024-04-03 11:05 UTC, gerebdavid commented on src/components/ui/BaseCard.vue
>          v-model="localTodo.priority"
v-model should be higher than class

2024-04-03 11:06 UTC, gerebdavid commented on src/components/ui/BaseCard.vue
> +        @on-checked="onTodoChecked"
do you need a click event here?

2024-04-03 11:07 UTC, gerebdavid commented on src/components/ui/BaseCard.vue
> +function onTodoChecked() {
why do you need a separate emit for todo checked? cant you use update-todo here?

2024-04-03 11:08 UTC, gerebdavid commented on src/components/ui/BaseCard.vue
>          v-model="localTodo.complete"
Either have v-model or on-checked emit, using both makes no sense

2024-04-03 11:08 UTC, gerebdavid commented on src/components/ui/BaseCheck.vue
> +  <div @click.stop="clickedSvg">
why do you need a click event on the div and another click event on the image?